<template>
  <div class="disclaimer">
    <h1 class="title">Disclaimer Policy</h1>
    <p class="text">We keep the Website (together referred to as “Platform”) up and running and free of annoyances. But we make no promises that we will succeed.</p>
    <p class="text">THE Firm IS PROVIDED “AS IS” AND “AS AVAILABLE” BASIS AND TO THE EXTENT PERMITTED BY LAW WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, IMPLIED WARRANTIES FOR A PARTICULAR PURPOSE, TITLE, AND NON-INFRINGEMENT. IN ADDITION, WHILE THE Firm ATTEMPTS TO PROVIDE A GOOD USER EXPERIENCE, WE DO NOT REPRESENT OR WARRANT THAT: (A) THE PLATFORM WILL ALWAYS BE SECURE AND ERROR-FREE, (B) THE PLATFORM WILL ALWAYS FUNCTION WITHOUT DELAYS, DISRUPTIONS, OR IMPERFECTIONS; OR (C) THAT ANY CONTENT, USER CONTENT, OR INFORMATION YOU OBTAIN ON OR THROUGH THE PLATFORM WILL BE TIMELY OR ACCURATE.</p>
    <p class="text">YOU UNDERSTAND AND AGREE THAT YOU MAY BE EXPOSED TO CONTENT THAT MIGHT BE OFFENSIVE, ILLEGAL, MISLEADING, OR OTHERWISE INAPPROPRIATE, NONE OF WHICH THE Firm WILL BE RESPONSIBLE FOR.</p>
    <p class="text">THE Firm WILL NOT BE RESPONSIBLE FOR ANY DAMAGE SUFFERED BY USERS FROM THE USE OF THE PLATFORM PROVIDED ON THE SERVICES AVAILABLE ON THE PLATFORM OR THE CONTENT ON THIS PLATFORM. THIS INCLUDES BUT IS NOT LIMITED TO LOSS OF REVENUE/DATA RESULTING FROM DELAYS, AS MAY OCCUR BECAUSE OF ANY ACT/OMISSION OF PARTIES. THIS DISCLAIMER OF LIABILITY ALSO APPLIES TO ANY DAMAGES OR INJURY CAUSED BY ANY FAILURE OF PERFORMANCE, ERROR, OMISSION, INTERRUPTION, DELETION, DEFECTS, DELAYS IN OPERATION OR TRANSMISSION, COMPUTER VIRUSES, COMMUNICATION LINE FAILURE, THEFT OR DESTRUCTION OR UNAUTHORIZED ACCESS TO, ALTERATION OF, OR USE OF RECORDS, WHETHER FOR BREACH OF CONTRACT, TORTUOUS BEHAVIOUR, NEGLIGENCE, OR UNDER ANY OTHER CAUSE OF ACTION.</p>
    <p class="text">THE Firm ALSO MAKES IT CLEAR THAT IT SHALL NOT BE HELD LIABLE FOR ANY DAMAGE/HURT/INCONVENIENCE CAUSED TO THE USER THROUGH THE COURSE OF USAGE OF THE PLATFORM AND/OR CONTENT OR AS A RESULT OF THE USERS’ ACTIONS. THE Firm MAKES NO REPRESENTATIONS OR WARRANTIES AS TO THE CONDUCT OF THE USERS.</p>
    <p class="text">THE CONTENT ON THE PLATFORM ARE INTENDED TO BE SUBJECT TO AVAILABILITY, WITHOUT ANY PROMISES OR GUARANTEES ON THE SAME BY THE Firm OR BY THE PLATFORM. WHILE CERTAIN INFORMATION AVAILABLE ON THE PLATFORM IS THE PROPERTY OF THE Firm AND THE Firm ENDEAVOURS TO KEEP THE SAID INFORMATION UPDATED AND ACCURATE, THE Firm SHALL NOT MAKE NO REPRESENTATIONS OR WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, ABOUT THE COMPLETENESS, ACCURACY, RELIABILITY, SUITABILITY OR AVAILABILITY WITH RESPECT TO THE PLATFORM OR THE INFORMATION, OR RELATED GRAPHICS CONTAINED ON THE PLATFORM FOR ANY PURPOSE. ANY RELIANCE YOU PLACE ON SUCH INFORMATION IS, THEREFORE STRICTLY AT YOUR OWN RISK.</p>
    <p class="text">THE Firm BEARS NO RESPONSIBILITY WHATSOEVER FOR ANY CONSEQUENCES ARISING FROM THE USE OF THE PLATFORM BY USERS. THE USE OF THE PLATFORM IS THE SOLE RESPONSIBILITY OF THE USER (OR LEGALLY AUTHORISED PERSON ON BEHALF OF THE USER), AND IN CASE OF ANY NEGLIGENCE ON THE PART OF THE USER IN ACTING ON THE SAME SHALL NOT BE CONSTRUED AS IMPOSING ANY LIABILITY, DIRECT OR INDIRECT, ON THE COMPANY/PLATFORM.</p>
    <p class="text">THE Firm SHALL DISCLAIM ALL RESPONSIBILITY AND OWNS NO LIABILITY TO USERS FOR ANY OUTCOME (INCIDENTAL, DIRECT, INDIRECT OR OTHERWISE) FROM THE USE OF THE PLATFORM. IN NO EVENT WILL THE Firm BE LIABLE FOR ANY LOSS OR DAMAGE, INCLUDING, WITHOUT LIMITATION, INDIRECT OR CONSEQUENTIAL LOSS OR DAMAGE, OR ANY LOSS OR DAMAGE WHATSOEVER ARISING FROM LOSS OF DATA OR PROFITS ARISING OUT OF, OR IN CONNECTION WITH, THE USE OF THE PLATFORM.</p>
    <p class="text">THROUGH THIS PLATFORM, YOU ARE ABLE TO LINK TO OTHER PLATFORMS WHICH IS NOT UNDER THE COMPANY’S CONTROL. WE HAVE NO CONTROL OVER THE NATURE, CONTENT AND AVAILABILITY OF THOSE SITES. THE INCLUSION OF ANY LINKS DOES NOT NECESSARILY IMPLY A RECOMMENDATION OR ENDORSE THE VIEWS EXPRESSED WITHIN THEM. EVERY EFFORT IS MADE TO KEEP THE PLATFORM & PLATFORM UP AND RUNNING SMOOTHLY. HOWEVER, THE Firm TAKES NO RESPONSIBILITY FOR, AND WILL NOT BE LIABLE FOR, THE PLATFORM BEING TEMPORARILY UNAVAILABLE DUE TO TECHNICAL ISSUES BEYOND OUR CONTROL.</p>
    <p class="text">TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, THE Firm WILL HAVE NO LIABILITY RELATED TO USER CONTENT ARISING UNDER INTELLECTUAL PROPERTY RIGHTS, LIBEL, PRIVACY, PUBLICITY, OBSCENITY OR OTHER LAWS. THE PLATFORM ALSO DISCLAIMS ALL LIABILITY WITH RESPECT TO THE MISUSE, LOSS, MODIFICATION OR UNAVAILABILITY OF ANY USER CONTENT.</p>
    <p class="text">THE USER UNDERSTANDS AND AGREES THAT ANY MATERIAL OR DATA DOWNLOADED OR OTHERWISE OBTAINED THROUGH THE PLATFORM ARE DONE ENTIRELY AT HIS/HER OWN DISCRETION AND RISK, AND HE/SHE WILL BE SOLELY RESPONSIBLE FOR ANY DAMAGE TO HIS/HER COMPUTER SYSTEMS OR LOSS OF DATA THAT RESULTS FROM THE DOWNLOAD OF SUCH MATERIAL OR DATA.</p>
  </div>
</template>
<style scoped>
.disclaimer {
  width: 90vw;
  margin: 1rem auto;
  max-width: 800px;
}
.title {
  font-size: 2rem;
  font-weight: 700;
  color: var(--primary-color);
  padding: 1rem 0;
}
.text{
  font-size: 1rem;
  font-weight: 400;
  color: var(--dark-color);
  padding: 0.5rem;
  text-align: justify;
}
</style>